#!/usr/bin/env ruby
require 'fileutils'

PROGNAME = File.basename(__FILE__)
MIGRATIONS_DIR = 'internal/praefect/db/migrations'

def main(migration_name)
  unless /\A[a-z0-9_]+\z/ =~ migration_name
    abort "invalid migration name #{migration_name.inspect} (only a-z0-9_ are allowed)"
  end

  sequence_number = Time.now.strftime('%Y%m%d%H%S')
  files = %w[up down].map do |direction|
    File.join(MIGRATIONS_DIR, "#{sequence_number}_#{migration_name}.#{direction}.sql")
  end

  FileUtils.touch(files, verbose: true)
end

unless ARGV.count == 1
  abort "usage: #{PROGNAME} MIGRATION_NAME"
end

main(*ARGV)
