// DO NOT EDIT; THIS FILE WAS GENERATED BY COMMAND: make dumb_repo_gen.go

package gitalox

import "gitlab.com/gitlab-org/gitaly-proto/go/gitalypb"
import "context"

func (drs *dummyRepoService) RepositoryExists(context.Context, *gitalypb.RepositoryExistsRequest) (*gitalypb.RepositoryExistsResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) RepackIncremental(context.Context, *gitalypb.RepackIncrementalRequest) (*gitalypb.RepackIncrementalResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) RepackFull(context.Context, *gitalypb.RepackFullRequest) (*gitalypb.RepackFullResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) GarbageCollect(context.Context, *gitalypb.GarbageCollectRequest) (*gitalypb.GarbageCollectResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) RepositorySize(context.Context, *gitalypb.RepositorySizeRequest) (*gitalypb.RepositorySizeResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) ApplyGitattributes(context.Context, *gitalypb.ApplyGitattributesRequest) (*gitalypb.ApplyGitattributesResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) FetchRemote(context.Context, *gitalypb.FetchRemoteRequest) (*gitalypb.FetchRemoteResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) CreateRepository(context.Context, *gitalypb.CreateRepositoryRequest) (*gitalypb.CreateRepositoryResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) GetArchive(*gitalypb.GetArchiveRequest, gitalypb.RepositoryService_GetArchiveServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) HasLocalBranches(context.Context, *gitalypb.HasLocalBranchesRequest) (*gitalypb.HasLocalBranchesResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) FetchSourceBranch(context.Context, *gitalypb.FetchSourceBranchRequest) (*gitalypb.FetchSourceBranchResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) Fsck(context.Context, *gitalypb.FsckRequest) (*gitalypb.FsckResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) WriteRef(context.Context, *gitalypb.WriteRefRequest) (*gitalypb.WriteRefResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) FindMergeBase(context.Context, *gitalypb.FindMergeBaseRequest) (*gitalypb.FindMergeBaseResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) CreateFork(context.Context, *gitalypb.CreateForkRequest) (*gitalypb.CreateForkResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) IsRebaseInProgress(context.Context, *gitalypb.IsRebaseInProgressRequest) (*gitalypb.IsRebaseInProgressResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) IsSquashInProgress(context.Context, *gitalypb.IsSquashInProgressRequest) (*gitalypb.IsSquashInProgressResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) CreateRepositoryFromURL(context.Context, *gitalypb.CreateRepositoryFromURLRequest) (*gitalypb.CreateRepositoryFromURLResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) CreateBundle(*gitalypb.CreateBundleRequest, gitalypb.RepositoryService_CreateBundleServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) CreateRepositoryFromBundle(gitalypb.RepositoryService_CreateRepositoryFromBundleServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) WriteConfig(context.Context, *gitalypb.WriteConfigRequest) (*gitalypb.WriteConfigResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) SetConfig(context.Context, *gitalypb.SetConfigRequest) (*gitalypb.SetConfigResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) DeleteConfig(context.Context, *gitalypb.DeleteConfigRequest) (*gitalypb.DeleteConfigResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) FindLicense(context.Context, *gitalypb.FindLicenseRequest) (*gitalypb.FindLicenseResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) GetInfoAttributes(*gitalypb.GetInfoAttributesRequest, gitalypb.RepositoryService_GetInfoAttributesServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) CalculateChecksum(context.Context, *gitalypb.CalculateChecksumRequest) (*gitalypb.CalculateChecksumResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) Cleanup(context.Context, *gitalypb.CleanupRequest) (*gitalypb.CleanupResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) GetSnapshot(*gitalypb.GetSnapshotRequest, gitalypb.RepositoryService_GetSnapshotServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) CreateRepositoryFromSnapshot(context.Context, *gitalypb.CreateRepositoryFromSnapshotRequest) (*gitalypb.CreateRepositoryFromSnapshotResponse, error) {
	panic("not implemented")
}

func (drs *dummyRepoService) GetRawChanges(*gitalypb.GetRawChangesRequest, gitalypb.RepositoryService_GetRawChangesServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) SearchFilesByContent(*gitalypb.SearchFilesByContentRequest, gitalypb.RepositoryService_SearchFilesByContentServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) SearchFilesByName(*gitalypb.SearchFilesByNameRequest, gitalypb.RepositoryService_SearchFilesByNameServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) RestoreCustomHooks(gitalypb.RepositoryService_RestoreCustomHooksServer) error {
	panic("not implemented")
}

func (drs *dummyRepoService) BackupCustomHooks(*gitalypb.BackupCustomHooksRequest, gitalypb.RepositoryService_BackupCustomHooksServer) error {
	panic("not implemented")
}
