---
lint:
  rules:
    all_default: true
    remove:
      # Our use of enums isn't conforming to best practices, and it's hard to
      # change retroactively. We may eventually enable these linters and then
      # create exceptions for preexisting definitions.
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      # We don't specify any line length limits.
      - MAX_LINE_LENGTH
      # Many of our definitions aren't commented at all. We want to eventually
      # opt-in to enable these linting warnings, but right now we just want to
      # get protolint included in our workflow with minimal required changes.
      - FILE_HAS_COMMENT
      - RPCS_HAVE_COMMENT
      - FIELDS_HAVE_COMMENT
      - SERVICES_HAVE_COMMENT
      - MESSAGES_HAVE_COMMENT
      - ENUMS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT
      # Many of our fields and messages have prepositions in them, and
      # furthermore this rule doesn't feel all that sensible after all. We thus
      # disable it.
      - FIELD_NAMES_EXCLUDE_PREPOSITIONS
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
