---
lint:
  rules:
    all_default: true
    remove:
      # We don't specify any line length limits.
      - MAX_LINE_LENGTH
      # We do not put comments in front of files. We already document services,
      # and only have a single service per file, so there is not much of a
      # point anyway.
      - FILE_HAS_COMMENT
      # Many of our fields and messages have prepositions in them, and
      # furthermore this rule doesn't feel all that sensible after all. We thus
      # disable it.
      - FIELD_NAMES_EXCLUDE_PREPOSITIONS
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
