// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hook.proto

package gitalypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReferenceTransactionHookRequest_State int32

const (
	ReferenceTransactionHookRequest_PREPARED  ReferenceTransactionHookRequest_State = 0
	ReferenceTransactionHookRequest_COMMITTED ReferenceTransactionHookRequest_State = 1
	ReferenceTransactionHookRequest_ABORTED   ReferenceTransactionHookRequest_State = 2
)

var ReferenceTransactionHookRequest_State_name = map[int32]string{
	0: "PREPARED",
	1: "COMMITTED",
	2: "ABORTED",
}

var ReferenceTransactionHookRequest_State_value = map[string]int32{
	"PREPARED":  0,
	"COMMITTED": 1,
	"ABORTED":   2,
}

func (x ReferenceTransactionHookRequest_State) String() string {
	return proto.EnumName(ReferenceTransactionHookRequest_State_name, int32(x))
}

func (ReferenceTransactionHookRequest_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{6, 0}
}

type PreReceiveHookRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	EnvironmentVariables []string    `protobuf:"bytes,2,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty"`
	Stdin                []byte      `protobuf:"bytes,4,opt,name=stdin,proto3" json:"stdin,omitempty"`
	GitPushOptions       []string    `protobuf:"bytes,5,rep,name=git_push_options,json=gitPushOptions,proto3" json:"git_push_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PreReceiveHookRequest) Reset()         { *m = PreReceiveHookRequest{} }
func (m *PreReceiveHookRequest) String() string { return proto.CompactTextString(m) }
func (*PreReceiveHookRequest) ProtoMessage()    {}
func (*PreReceiveHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{0}
}

func (m *PreReceiveHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreReceiveHookRequest.Unmarshal(m, b)
}
func (m *PreReceiveHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreReceiveHookRequest.Marshal(b, m, deterministic)
}
func (m *PreReceiveHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreReceiveHookRequest.Merge(m, src)
}
func (m *PreReceiveHookRequest) XXX_Size() int {
	return xxx_messageInfo_PreReceiveHookRequest.Size(m)
}
func (m *PreReceiveHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreReceiveHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreReceiveHookRequest proto.InternalMessageInfo

func (m *PreReceiveHookRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *PreReceiveHookRequest) GetEnvironmentVariables() []string {
	if m != nil {
		return m.EnvironmentVariables
	}
	return nil
}

func (m *PreReceiveHookRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

func (m *PreReceiveHookRequest) GetGitPushOptions() []string {
	if m != nil {
		return m.GitPushOptions
	}
	return nil
}

type PreReceiveHookResponse struct {
	Stdout               []byte      `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte      `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitStatus           *ExitStatus `protobuf:"bytes,3,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PreReceiveHookResponse) Reset()         { *m = PreReceiveHookResponse{} }
func (m *PreReceiveHookResponse) String() string { return proto.CompactTextString(m) }
func (*PreReceiveHookResponse) ProtoMessage()    {}
func (*PreReceiveHookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{1}
}

func (m *PreReceiveHookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreReceiveHookResponse.Unmarshal(m, b)
}
func (m *PreReceiveHookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreReceiveHookResponse.Marshal(b, m, deterministic)
}
func (m *PreReceiveHookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreReceiveHookResponse.Merge(m, src)
}
func (m *PreReceiveHookResponse) XXX_Size() int {
	return xxx_messageInfo_PreReceiveHookResponse.Size(m)
}
func (m *PreReceiveHookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PreReceiveHookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PreReceiveHookResponse proto.InternalMessageInfo

func (m *PreReceiveHookResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *PreReceiveHookResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *PreReceiveHookResponse) GetExitStatus() *ExitStatus {
	if m != nil {
		return m.ExitStatus
	}
	return nil
}

type PostReceiveHookRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	EnvironmentVariables []string    `protobuf:"bytes,2,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty"`
	Stdin                []byte      `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	GitPushOptions       []string    `protobuf:"bytes,4,rep,name=git_push_options,json=gitPushOptions,proto3" json:"git_push_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PostReceiveHookRequest) Reset()         { *m = PostReceiveHookRequest{} }
func (m *PostReceiveHookRequest) String() string { return proto.CompactTextString(m) }
func (*PostReceiveHookRequest) ProtoMessage()    {}
func (*PostReceiveHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{2}
}

func (m *PostReceiveHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReceiveHookRequest.Unmarshal(m, b)
}
func (m *PostReceiveHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReceiveHookRequest.Marshal(b, m, deterministic)
}
func (m *PostReceiveHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReceiveHookRequest.Merge(m, src)
}
func (m *PostReceiveHookRequest) XXX_Size() int {
	return xxx_messageInfo_PostReceiveHookRequest.Size(m)
}
func (m *PostReceiveHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReceiveHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostReceiveHookRequest proto.InternalMessageInfo

func (m *PostReceiveHookRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *PostReceiveHookRequest) GetEnvironmentVariables() []string {
	if m != nil {
		return m.EnvironmentVariables
	}
	return nil
}

func (m *PostReceiveHookRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

func (m *PostReceiveHookRequest) GetGitPushOptions() []string {
	if m != nil {
		return m.GitPushOptions
	}
	return nil
}

type PostReceiveHookResponse struct {
	Stdout               []byte      `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte      `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitStatus           *ExitStatus `protobuf:"bytes,3,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PostReceiveHookResponse) Reset()         { *m = PostReceiveHookResponse{} }
func (m *PostReceiveHookResponse) String() string { return proto.CompactTextString(m) }
func (*PostReceiveHookResponse) ProtoMessage()    {}
func (*PostReceiveHookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{3}
}

func (m *PostReceiveHookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReceiveHookResponse.Unmarshal(m, b)
}
func (m *PostReceiveHookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReceiveHookResponse.Marshal(b, m, deterministic)
}
func (m *PostReceiveHookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReceiveHookResponse.Merge(m, src)
}
func (m *PostReceiveHookResponse) XXX_Size() int {
	return xxx_messageInfo_PostReceiveHookResponse.Size(m)
}
func (m *PostReceiveHookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReceiveHookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostReceiveHookResponse proto.InternalMessageInfo

func (m *PostReceiveHookResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *PostReceiveHookResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *PostReceiveHookResponse) GetExitStatus() *ExitStatus {
	if m != nil {
		return m.ExitStatus
	}
	return nil
}

type UpdateHookRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	EnvironmentVariables []string    `protobuf:"bytes,2,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty"`
	Ref                  []byte      `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	OldValue             string      `protobuf:"bytes,4,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue             string      `protobuf:"bytes,5,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateHookRequest) Reset()         { *m = UpdateHookRequest{} }
func (m *UpdateHookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHookRequest) ProtoMessage()    {}
func (*UpdateHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{4}
}

func (m *UpdateHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHookRequest.Unmarshal(m, b)
}
func (m *UpdateHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHookRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHookRequest.Merge(m, src)
}
func (m *UpdateHookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHookRequest.Size(m)
}
func (m *UpdateHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHookRequest proto.InternalMessageInfo

func (m *UpdateHookRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *UpdateHookRequest) GetEnvironmentVariables() []string {
	if m != nil {
		return m.EnvironmentVariables
	}
	return nil
}

func (m *UpdateHookRequest) GetRef() []byte {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *UpdateHookRequest) GetOldValue() string {
	if m != nil {
		return m.OldValue
	}
	return ""
}

func (m *UpdateHookRequest) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

type UpdateHookResponse struct {
	Stdout               []byte      `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte      `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitStatus           *ExitStatus `protobuf:"bytes,3,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateHookResponse) Reset()         { *m = UpdateHookResponse{} }
func (m *UpdateHookResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateHookResponse) ProtoMessage()    {}
func (*UpdateHookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{5}
}

func (m *UpdateHookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHookResponse.Unmarshal(m, b)
}
func (m *UpdateHookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHookResponse.Marshal(b, m, deterministic)
}
func (m *UpdateHookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHookResponse.Merge(m, src)
}
func (m *UpdateHookResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateHookResponse.Size(m)
}
func (m *UpdateHookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHookResponse proto.InternalMessageInfo

func (m *UpdateHookResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *UpdateHookResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *UpdateHookResponse) GetExitStatus() *ExitStatus {
	if m != nil {
		return m.ExitStatus
	}
	return nil
}

type ReferenceTransactionHookRequest struct {
	Repository           *Repository                           `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	EnvironmentVariables []string                              `protobuf:"bytes,2,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty"`
	Stdin                []byte                                `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	State                ReferenceTransactionHookRequest_State `protobuf:"varint,4,opt,name=state,proto3,enum=gitaly.ReferenceTransactionHookRequest_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ReferenceTransactionHookRequest) Reset()         { *m = ReferenceTransactionHookRequest{} }
func (m *ReferenceTransactionHookRequest) String() string { return proto.CompactTextString(m) }
func (*ReferenceTransactionHookRequest) ProtoMessage()    {}
func (*ReferenceTransactionHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{6}
}

func (m *ReferenceTransactionHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceTransactionHookRequest.Unmarshal(m, b)
}
func (m *ReferenceTransactionHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceTransactionHookRequest.Marshal(b, m, deterministic)
}
func (m *ReferenceTransactionHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceTransactionHookRequest.Merge(m, src)
}
func (m *ReferenceTransactionHookRequest) XXX_Size() int {
	return xxx_messageInfo_ReferenceTransactionHookRequest.Size(m)
}
func (m *ReferenceTransactionHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceTransactionHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceTransactionHookRequest proto.InternalMessageInfo

func (m *ReferenceTransactionHookRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *ReferenceTransactionHookRequest) GetEnvironmentVariables() []string {
	if m != nil {
		return m.EnvironmentVariables
	}
	return nil
}

func (m *ReferenceTransactionHookRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

func (m *ReferenceTransactionHookRequest) GetState() ReferenceTransactionHookRequest_State {
	if m != nil {
		return m.State
	}
	return ReferenceTransactionHookRequest_PREPARED
}

type ReferenceTransactionHookResponse struct {
	Stdout               []byte      `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte      `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitStatus           *ExitStatus `protobuf:"bytes,3,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReferenceTransactionHookResponse) Reset()         { *m = ReferenceTransactionHookResponse{} }
func (m *ReferenceTransactionHookResponse) String() string { return proto.CompactTextString(m) }
func (*ReferenceTransactionHookResponse) ProtoMessage()    {}
func (*ReferenceTransactionHookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{7}
}

func (m *ReferenceTransactionHookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceTransactionHookResponse.Unmarshal(m, b)
}
func (m *ReferenceTransactionHookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceTransactionHookResponse.Marshal(b, m, deterministic)
}
func (m *ReferenceTransactionHookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceTransactionHookResponse.Merge(m, src)
}
func (m *ReferenceTransactionHookResponse) XXX_Size() int {
	return xxx_messageInfo_ReferenceTransactionHookResponse.Size(m)
}
func (m *ReferenceTransactionHookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceTransactionHookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceTransactionHookResponse proto.InternalMessageInfo

func (m *ReferenceTransactionHookResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *ReferenceTransactionHookResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *ReferenceTransactionHookResponse) GetExitStatus() *ExitStatus {
	if m != nil {
		return m.ExitStatus
	}
	return nil
}

type PackObjectsHookRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Args                 []string    `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Stdin                []byte      `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PackObjectsHookRequest) Reset()         { *m = PackObjectsHookRequest{} }
func (m *PackObjectsHookRequest) String() string { return proto.CompactTextString(m) }
func (*PackObjectsHookRequest) ProtoMessage()    {}
func (*PackObjectsHookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{8}
}

func (m *PackObjectsHookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackObjectsHookRequest.Unmarshal(m, b)
}
func (m *PackObjectsHookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackObjectsHookRequest.Marshal(b, m, deterministic)
}
func (m *PackObjectsHookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackObjectsHookRequest.Merge(m, src)
}
func (m *PackObjectsHookRequest) XXX_Size() int {
	return xxx_messageInfo_PackObjectsHookRequest.Size(m)
}
func (m *PackObjectsHookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PackObjectsHookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PackObjectsHookRequest proto.InternalMessageInfo

func (m *PackObjectsHookRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *PackObjectsHookRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *PackObjectsHookRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

type PackObjectsHookResponse struct {
	CommandAccepted      bool        `protobuf:"varint,1,opt,name=command_accepted,json=commandAccepted,proto3" json:"command_accepted,omitempty"`
	Stdout               []byte      `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               []byte      `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitStatus           *ExitStatus `protobuf:"bytes,4,opt,name=exit_status,json=exitStatus,proto3" json:"exit_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PackObjectsHookResponse) Reset()         { *m = PackObjectsHookResponse{} }
func (m *PackObjectsHookResponse) String() string { return proto.CompactTextString(m) }
func (*PackObjectsHookResponse) ProtoMessage()    {}
func (*PackObjectsHookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eef30da1c11ee1b, []int{9}
}

func (m *PackObjectsHookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackObjectsHookResponse.Unmarshal(m, b)
}
func (m *PackObjectsHookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackObjectsHookResponse.Marshal(b, m, deterministic)
}
func (m *PackObjectsHookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackObjectsHookResponse.Merge(m, src)
}
func (m *PackObjectsHookResponse) XXX_Size() int {
	return xxx_messageInfo_PackObjectsHookResponse.Size(m)
}
func (m *PackObjectsHookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PackObjectsHookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PackObjectsHookResponse proto.InternalMessageInfo

func (m *PackObjectsHookResponse) GetCommandAccepted() bool {
	if m != nil {
		return m.CommandAccepted
	}
	return false
}

func (m *PackObjectsHookResponse) GetStdout() []byte {
	if m != nil {
		return m.Stdout
	}
	return nil
}

func (m *PackObjectsHookResponse) GetStderr() []byte {
	if m != nil {
		return m.Stderr
	}
	return nil
}

func (m *PackObjectsHookResponse) GetExitStatus() *ExitStatus {
	if m != nil {
		return m.ExitStatus
	}
	return nil
}

func init() {
	proto.RegisterEnum("gitaly.ReferenceTransactionHookRequest_State", ReferenceTransactionHookRequest_State_name, ReferenceTransactionHookRequest_State_value)
	proto.RegisterType((*PreReceiveHookRequest)(nil), "gitaly.PreReceiveHookRequest")
	proto.RegisterType((*PreReceiveHookResponse)(nil), "gitaly.PreReceiveHookResponse")
	proto.RegisterType((*PostReceiveHookRequest)(nil), "gitaly.PostReceiveHookRequest")
	proto.RegisterType((*PostReceiveHookResponse)(nil), "gitaly.PostReceiveHookResponse")
	proto.RegisterType((*UpdateHookRequest)(nil), "gitaly.UpdateHookRequest")
	proto.RegisterType((*UpdateHookResponse)(nil), "gitaly.UpdateHookResponse")
	proto.RegisterType((*ReferenceTransactionHookRequest)(nil), "gitaly.ReferenceTransactionHookRequest")
	proto.RegisterType((*ReferenceTransactionHookResponse)(nil), "gitaly.ReferenceTransactionHookResponse")
	proto.RegisterType((*PackObjectsHookRequest)(nil), "gitaly.PackObjectsHookRequest")
	proto.RegisterType((*PackObjectsHookResponse)(nil), "gitaly.PackObjectsHookResponse")
}

func init() { proto.RegisterFile("hook.proto", fileDescriptor_3eef30da1c11ee1b) }

var fileDescriptor_3eef30da1c11ee1b = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0xcd, 0x52, 0x13, 0x41,
	0x10, 0xc7, 0xdd, 0x7c, 0x99, 0x74, 0x22, 0xc4, 0x29, 0x08, 0x31, 0x96, 0x92, 0xda, 0x8b, 0xb1,
	0x4a, 0x12, 0x84, 0x8b, 0x57, 0x3e, 0x52, 0xa5, 0x07, 0x2a, 0xa9, 0x01, 0x39, 0x68, 0x95, 0xa9,
	0xc9, 0x6e, 0x93, 0xac, 0x6c, 0x76, 0xd6, 0x99, 0x49, 0x20, 0x55, 0xea, 0xd5, 0x47, 0xd0, 0x93,
	0x77, 0x5f, 0x04, 0x6f, 0x3e, 0x8d, 0x27, 0x4f, 0xd6, 0x7e, 0x04, 0x36, 0xb0, 0x01, 0x0e, 0x16,
	0x72, 0x9b, 0xee, 0xff, 0x4c, 0xcf, 0xf4, 0xaf, 0x3b, 0x9d, 0x05, 0xe8, 0x73, 0x7e, 0x58, 0x77,
	0x05, 0x57, 0x9c, 0x64, 0x7a, 0x96, 0x62, 0xf6, 0xb8, 0x02, 0xb6, 0xe5, 0xa8, 0xc0, 0x57, 0x29,
	0xc8, 0x3e, 0x13, 0x68, 0x06, 0x96, 0x7e, 0xa2, 0xc1, 0x62, 0x5b, 0x20, 0x45, 0x03, 0xad, 0x11,
	0xbe, 0xe4, 0xfc, 0x90, 0xe2, 0x87, 0x21, 0x4a, 0x45, 0x5e, 0x00, 0x08, 0x74, 0xb9, 0xb4, 0x14,
	0x17, 0xe3, 0xb2, 0x56, 0xd5, 0x6a, 0xf9, 0x35, 0x52, 0x0f, 0x02, 0xd6, 0xe9, 0xa9, 0xb2, 0x99,
	0xfa, 0x76, 0xf2, 0x4c, 0xa3, 0x91, 0xbd, 0x64, 0x1d, 0x16, 0xd1, 0x19, 0x59, 0x82, 0x3b, 0x03,
	0x74, 0x54, 0x67, 0xc4, 0x84, 0xc5, 0xba, 0x36, 0xca, 0x72, 0xa2, 0x9a, 0xac, 0xe5, 0xe8, 0x42,
	0x44, 0xdc, 0x9f, 0x68, 0x64, 0x01, 0xd2, 0x52, 0x99, 0x96, 0x53, 0x4e, 0x55, 0xb5, 0x5a, 0x81,
	0x06, 0x06, 0xa9, 0x41, 0xb1, 0x67, 0xa9, 0x8e, 0x3b, 0x94, 0xfd, 0x0e, 0x77, 0x95, 0xc5, 0x1d,
	0x59, 0x4e, 0xfb, 0x51, 0xe6, 0x7a, 0x96, 0x6a, 0x0f, 0x65, 0xbf, 0x15, 0x78, 0xf5, 0x4f, 0x50,
	0x3a, 0x9f, 0x87, 0x74, 0xb9, 0x23, 0x91, 0x94, 0x20, 0x23, 0x95, 0xc9, 0x87, 0xca, 0x4f, 0xa2,
	0x40, 0x43, 0x2b, 0xf4, 0xa3, 0x10, 0xe5, 0xc4, 0xa9, 0x1f, 0x85, 0x20, 0xeb, 0x90, 0xc7, 0x63,
	0x4b, 0x75, 0xa4, 0x62, 0x6a, 0x28, 0xcb, 0xc9, 0xe9, 0xcc, 0x9b, 0xc7, 0x96, 0xda, 0xf5, 0x15,
	0x0a, 0x78, 0xba, 0xd6, 0x7f, 0x6a, 0x50, 0x6a, 0x73, 0xa9, 0x6e, 0x11, 0xc8, 0xe4, 0x55, 0x20,
	0x53, 0xb1, 0x20, 0x3f, 0xc3, 0xd2, 0x85, 0x44, 0x6e, 0x92, 0xe4, 0x2f, 0x0d, 0xee, 0xbf, 0x76,
	0x4d, 0xa6, 0xfe, 0x27, 0xc4, 0x22, 0x24, 0x05, 0x1e, 0x84, 0x08, 0xbd, 0x25, 0x79, 0x08, 0x39,
	0x6e, 0x9b, 0x9d, 0x11, 0xb3, 0x87, 0xe8, 0xf7, 0x68, 0x8e, 0x66, 0xb9, 0x6d, 0xee, 0x7b, 0xb6,
	0x27, 0x3a, 0x78, 0x14, 0x8a, 0xe9, 0x40, 0x74, 0xf0, 0xc8, 0x17, 0xf5, 0x31, 0x90, 0x68, 0x3e,
	0x37, 0xc9, 0xf2, 0x7b, 0x02, 0x96, 0x29, 0x1e, 0xa0, 0x40, 0xc7, 0xc0, 0x3d, 0xc1, 0x1c, 0xc9,
	0x0c, 0xaf, 0xca, 0xb7, 0xae, 0x3d, 0xb7, 0x3c, 0x2f, 0x53, 0x01, 0xd9, 0xb9, 0xb5, 0x95, 0xb3,
	0xfb, 0x2f, 0x7d, 0x7c, 0xdd, 0xcb, 0x13, 0x69, 0x70, 0x56, 0x7f, 0x0e, 0x69, 0xdf, 0x26, 0x05,
	0xc8, 0xb6, 0x69, 0xb3, 0xbd, 0x41, 0x9b, 0xdb, 0xc5, 0x3b, 0xe4, 0x1e, 0xe4, 0xb6, 0x5a, 0x3b,
	0x3b, 0xaf, 0xf6, 0xf6, 0x9a, 0xdb, 0x45, 0x8d, 0xe4, 0xe1, 0xee, 0xc6, 0x66, 0x8b, 0x7a, 0x46,
	0x42, 0xff, 0xa2, 0x41, 0x75, 0xf6, 0x1d, 0x37, 0x59, 0xaa, 0x8f, 0x50, 0x6a, 0x33, 0xe3, 0xb0,
	0xd5, 0x7d, 0x8f, 0x86, 0x92, 0xff, 0xa6, 0x40, 0x04, 0x52, 0x4c, 0xf4, 0x26, 0xf5, 0xf0, 0xd7,
	0xf1, 0xfc, 0xf5, 0x1f, 0x1a, 0x2c, 0x5d, 0xb8, 0x3e, 0x4c, 0xff, 0x29, 0x14, 0x0d, 0x3e, 0x18,
	0x30, 0xc7, 0xec, 0x30, 0xc3, 0x40, 0x57, 0xa1, 0xe9, 0xbf, 0x22, 0x4b, 0xe7, 0x43, 0xff, 0x46,
	0xe8, 0x8e, 0x90, 0x4a, 0xcc, 0x20, 0x95, 0xbc, 0x8c, 0x54, 0xea, 0x3a, 0xa4, 0xd6, 0x7e, 0x27,
	0x21, 0xef, 0x3d, 0x70, 0x17, 0xc5, 0xc8, 0x32, 0x90, 0xbc, 0x85, 0xb9, 0xe9, 0xc9, 0x4f, 0x1e,
	0x4d, 0x22, 0xc4, 0xfe, 0xb3, 0x55, 0x1e, 0xcf, 0x92, 0x83, 0x84, 0xf5, 0xcc, 0x9f, 0xaf, 0xb5,
	0x44, 0x36, 0x51, 0xd3, 0x56, 0x35, 0xf2, 0x0e, 0xe6, 0xcf, 0x4d, 0x43, 0x72, 0x76, 0x3c, 0x76,
	0xde, 0x57, 0x96, 0x67, 0xea, 0x31, 0xf1, 0x77, 0x00, 0xce, 0x86, 0x03, 0x79, 0x30, 0x39, 0x7a,
	0x61, 0x00, 0x56, 0x2a, 0x71, 0xd2, 0x74, 0xc0, 0x55, 0x8d, 0x8c, 0xa1, 0x3c, 0xab, 0x9d, 0xc9,
	0x93, 0x6b, 0xfe, 0xa8, 0x2a, 0xb5, 0xab, 0x37, 0xce, 0x20, 0x35, 0xdd, 0x41, 0x11, 0x52, 0xb1,
	0x9d, 0x1d, 0x21, 0x15, 0xdf, 0x7a, 0xd1, 0xf8, 0x9b, 0xab, 0x6f, 0xbc, 0xdd, 0x36, 0xeb, 0xd6,
	0x0d, 0x3e, 0x68, 0x04, 0xcb, 0x15, 0x2e, 0x7a, 0x8d, 0x20, 0x46, 0xc3, 0xff, 0x9e, 0x69, 0xf4,
	0x78, 0x68, 0xbb, 0xdd, 0x6e, 0xc6, 0x77, 0xad, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x3a,
	0x8a, 0x43, 0x12, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HookServiceClient is the client API for HookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HookServiceClient interface {
	PreReceiveHook(ctx context.Context, opts ...grpc.CallOption) (HookService_PreReceiveHookClient, error)
	PostReceiveHook(ctx context.Context, opts ...grpc.CallOption) (HookService_PostReceiveHookClient, error)
	UpdateHook(ctx context.Context, in *UpdateHookRequest, opts ...grpc.CallOption) (HookService_UpdateHookClient, error)
	ReferenceTransactionHook(ctx context.Context, opts ...grpc.CallOption) (HookService_ReferenceTransactionHookClient, error)
	PackObjectsHook(ctx context.Context, opts ...grpc.CallOption) (HookService_PackObjectsHookClient, error)
}

type hookServiceClient struct {
	cc *grpc.ClientConn
}

func NewHookServiceClient(cc *grpc.ClientConn) HookServiceClient {
	return &hookServiceClient{cc}
}

func (c *hookServiceClient) PreReceiveHook(ctx context.Context, opts ...grpc.CallOption) (HookService_PreReceiveHookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HookService_serviceDesc.Streams[0], "/gitaly.HookService/PreReceiveHook", opts...)
	if err != nil {
		return nil, err
	}
	x := &hookServicePreReceiveHookClient{stream}
	return x, nil
}

type HookService_PreReceiveHookClient interface {
	Send(*PreReceiveHookRequest) error
	Recv() (*PreReceiveHookResponse, error)
	grpc.ClientStream
}

type hookServicePreReceiveHookClient struct {
	grpc.ClientStream
}

func (x *hookServicePreReceiveHookClient) Send(m *PreReceiveHookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hookServicePreReceiveHookClient) Recv() (*PreReceiveHookResponse, error) {
	m := new(PreReceiveHookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hookServiceClient) PostReceiveHook(ctx context.Context, opts ...grpc.CallOption) (HookService_PostReceiveHookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HookService_serviceDesc.Streams[1], "/gitaly.HookService/PostReceiveHook", opts...)
	if err != nil {
		return nil, err
	}
	x := &hookServicePostReceiveHookClient{stream}
	return x, nil
}

type HookService_PostReceiveHookClient interface {
	Send(*PostReceiveHookRequest) error
	Recv() (*PostReceiveHookResponse, error)
	grpc.ClientStream
}

type hookServicePostReceiveHookClient struct {
	grpc.ClientStream
}

func (x *hookServicePostReceiveHookClient) Send(m *PostReceiveHookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hookServicePostReceiveHookClient) Recv() (*PostReceiveHookResponse, error) {
	m := new(PostReceiveHookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hookServiceClient) UpdateHook(ctx context.Context, in *UpdateHookRequest, opts ...grpc.CallOption) (HookService_UpdateHookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HookService_serviceDesc.Streams[2], "/gitaly.HookService/UpdateHook", opts...)
	if err != nil {
		return nil, err
	}
	x := &hookServiceUpdateHookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HookService_UpdateHookClient interface {
	Recv() (*UpdateHookResponse, error)
	grpc.ClientStream
}

type hookServiceUpdateHookClient struct {
	grpc.ClientStream
}

func (x *hookServiceUpdateHookClient) Recv() (*UpdateHookResponse, error) {
	m := new(UpdateHookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hookServiceClient) ReferenceTransactionHook(ctx context.Context, opts ...grpc.CallOption) (HookService_ReferenceTransactionHookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HookService_serviceDesc.Streams[3], "/gitaly.HookService/ReferenceTransactionHook", opts...)
	if err != nil {
		return nil, err
	}
	x := &hookServiceReferenceTransactionHookClient{stream}
	return x, nil
}

type HookService_ReferenceTransactionHookClient interface {
	Send(*ReferenceTransactionHookRequest) error
	Recv() (*ReferenceTransactionHookResponse, error)
	grpc.ClientStream
}

type hookServiceReferenceTransactionHookClient struct {
	grpc.ClientStream
}

func (x *hookServiceReferenceTransactionHookClient) Send(m *ReferenceTransactionHookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hookServiceReferenceTransactionHookClient) Recv() (*ReferenceTransactionHookResponse, error) {
	m := new(ReferenceTransactionHookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hookServiceClient) PackObjectsHook(ctx context.Context, opts ...grpc.CallOption) (HookService_PackObjectsHookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HookService_serviceDesc.Streams[4], "/gitaly.HookService/PackObjectsHook", opts...)
	if err != nil {
		return nil, err
	}
	x := &hookServicePackObjectsHookClient{stream}
	return x, nil
}

type HookService_PackObjectsHookClient interface {
	Send(*PackObjectsHookRequest) error
	Recv() (*PackObjectsHookResponse, error)
	grpc.ClientStream
}

type hookServicePackObjectsHookClient struct {
	grpc.ClientStream
}

func (x *hookServicePackObjectsHookClient) Send(m *PackObjectsHookRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hookServicePackObjectsHookClient) Recv() (*PackObjectsHookResponse, error) {
	m := new(PackObjectsHookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HookServiceServer is the server API for HookService service.
type HookServiceServer interface {
	PreReceiveHook(HookService_PreReceiveHookServer) error
	PostReceiveHook(HookService_PostReceiveHookServer) error
	UpdateHook(*UpdateHookRequest, HookService_UpdateHookServer) error
	ReferenceTransactionHook(HookService_ReferenceTransactionHookServer) error
	PackObjectsHook(HookService_PackObjectsHookServer) error
}

// UnimplementedHookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHookServiceServer struct {
}

func (*UnimplementedHookServiceServer) PreReceiveHook(srv HookService_PreReceiveHookServer) error {
	return status.Errorf(codes.Unimplemented, "method PreReceiveHook not implemented")
}
func (*UnimplementedHookServiceServer) PostReceiveHook(srv HookService_PostReceiveHookServer) error {
	return status.Errorf(codes.Unimplemented, "method PostReceiveHook not implemented")
}
func (*UnimplementedHookServiceServer) UpdateHook(req *UpdateHookRequest, srv HookService_UpdateHookServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateHook not implemented")
}
func (*UnimplementedHookServiceServer) ReferenceTransactionHook(srv HookService_ReferenceTransactionHookServer) error {
	return status.Errorf(codes.Unimplemented, "method ReferenceTransactionHook not implemented")
}
func (*UnimplementedHookServiceServer) PackObjectsHook(srv HookService_PackObjectsHookServer) error {
	return status.Errorf(codes.Unimplemented, "method PackObjectsHook not implemented")
}

func RegisterHookServiceServer(s *grpc.Server, srv HookServiceServer) {
	s.RegisterService(&_HookService_serviceDesc, srv)
}

func _HookService_PreReceiveHook_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HookServiceServer).PreReceiveHook(&hookServicePreReceiveHookServer{stream})
}

type HookService_PreReceiveHookServer interface {
	Send(*PreReceiveHookResponse) error
	Recv() (*PreReceiveHookRequest, error)
	grpc.ServerStream
}

type hookServicePreReceiveHookServer struct {
	grpc.ServerStream
}

func (x *hookServicePreReceiveHookServer) Send(m *PreReceiveHookResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hookServicePreReceiveHookServer) Recv() (*PreReceiveHookRequest, error) {
	m := new(PreReceiveHookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HookService_PostReceiveHook_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HookServiceServer).PostReceiveHook(&hookServicePostReceiveHookServer{stream})
}

type HookService_PostReceiveHookServer interface {
	Send(*PostReceiveHookResponse) error
	Recv() (*PostReceiveHookRequest, error)
	grpc.ServerStream
}

type hookServicePostReceiveHookServer struct {
	grpc.ServerStream
}

func (x *hookServicePostReceiveHookServer) Send(m *PostReceiveHookResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hookServicePostReceiveHookServer) Recv() (*PostReceiveHookRequest, error) {
	m := new(PostReceiveHookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HookService_UpdateHook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateHookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HookServiceServer).UpdateHook(m, &hookServiceUpdateHookServer{stream})
}

type HookService_UpdateHookServer interface {
	Send(*UpdateHookResponse) error
	grpc.ServerStream
}

type hookServiceUpdateHookServer struct {
	grpc.ServerStream
}

func (x *hookServiceUpdateHookServer) Send(m *UpdateHookResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HookService_ReferenceTransactionHook_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HookServiceServer).ReferenceTransactionHook(&hookServiceReferenceTransactionHookServer{stream})
}

type HookService_ReferenceTransactionHookServer interface {
	Send(*ReferenceTransactionHookResponse) error
	Recv() (*ReferenceTransactionHookRequest, error)
	grpc.ServerStream
}

type hookServiceReferenceTransactionHookServer struct {
	grpc.ServerStream
}

func (x *hookServiceReferenceTransactionHookServer) Send(m *ReferenceTransactionHookResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hookServiceReferenceTransactionHookServer) Recv() (*ReferenceTransactionHookRequest, error) {
	m := new(ReferenceTransactionHookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HookService_PackObjectsHook_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HookServiceServer).PackObjectsHook(&hookServicePackObjectsHookServer{stream})
}

type HookService_PackObjectsHookServer interface {
	Send(*PackObjectsHookResponse) error
	Recv() (*PackObjectsHookRequest, error)
	grpc.ServerStream
}

type hookServicePackObjectsHookServer struct {
	grpc.ServerStream
}

func (x *hookServicePackObjectsHookServer) Send(m *PackObjectsHookResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hookServicePackObjectsHookServer) Recv() (*PackObjectsHookRequest, error) {
	m := new(PackObjectsHookRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _HookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.HookService",
	HandlerType: (*HookServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PreReceiveHook",
			Handler:       _HookService_PreReceiveHook_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PostReceiveHook",
			Handler:       _HookService_PostReceiveHook_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateHook",
			Handler:       _HookService_UpdateHook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReferenceTransactionHook",
			Handler:       _HookService_ReferenceTransactionHook_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PackObjectsHook",
			Handler:       _HookService_PackObjectsHook_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hook.proto",
}
